# Generated by Django 3.0.6 on 2020-05-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyProfiles', '0004_auto_20200520_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agriculture',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='construction',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='cyber',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='excess',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='large',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='managementLiab',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='manufacturing',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='middleMarket',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='proLiab',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='product',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='prop',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='publicEntity',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='realEstate',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='retail',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='smb',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='tech',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='transportation',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='trucking',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='wcom',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='wholesale',
            field=models.BooleanField(),
        ),
    ]
