# Generated by Django 3.0.6 on 2020-05-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyProfiles', '0005_auto_20200520_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='phone',
            new_name='p1',
        ),
        migrations.AddField(
            model_name='agent',
            name='p2',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
