# Generated by Django 3.0.6 on 2020-05-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyProfiles', '0006_auto_20200520_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='password',
            field=models.TextField(default='boner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='username',
            field=models.TextField(default='pizza'),
            preserve_default=False,
        ),
    ]
